In [2]:
%pip install od pandas numpy

Defaulting to user installation because normal site-packages is not writeable
Collecting od
  Downloading od-2.0.2-py3-none-any.whl.metadata (1.9 kB)
Collecting pandas
  Downloading pandas-2.2.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 870.0 kB/s eta 0:00:00 0:00:01
Collecting numpy
  Downloading numpy-2.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 1.4 MB/s eta 0:00:00:00:01
Requirement already satisfied: python-dateutil>=2.8.2 in /home/seba/.local/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas) (2024.1)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.1-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading od-2.0.2-py3-none-any.whl (3.5 kB)
Downloading pandas-2.2.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 22.2 MB/s eta 0:00:0000:0100:01
Downloading numpy-2.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 23.9 MB/s eta 0:00:0000:0100:01
Downloading tzdata-2025.1-py2.py3-none-any.whl (346 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 346.8/346.8 kB 14.2 MB/s eta 0:00:00
Installing collected packages: tzdata, od, numpy, pandas
Successfully installed numpy-2.2.2 od-2.0.2 pandas-2.2.3 tzdata-2025.1
Note: you may need to restart the kernel to use updated packages.

In [3]:
import os
import pandas as pd
import numpy as np

In [4]:
os.environ['DATASET'] = "UPB2015"

In [5]:

sent_messages = pd.read_csv(
    f"dataset/{os.environ.get('DATASET')}/sent_messages.csv"
)
print(f"sent_messages columns: {sent_messages.columns}")

sent_messages columns: Index(['messageId', 'messageSource', 'messageHopCount', 'oldRelayId',
       'oldFriendWithDestination', 'oldRelayBattery', 'oldCommonCommunity',
       'oldDataMemory', 'newRelayId', 'newFriendWithDestination',
       'newRelayBattery', 'newCommonCommunity', 'newDataMemory'],
      dtype='object')

In [6]:
sent_messages

,messageId,messageSource,messageHopCount,oldRelayId,oldFriendWithDestination,oldRelayBattery,oldCommonCommunity,oldDataMemory,newRelayId,newFriendWithDestination,newRelayBattery,newCommonCommunity,newDataMemory
0,18,3,1,5,1,0.333218,0,0.006,3,1,0.550437,0,0.00
1,19,3,1,5,1,0.333218,0,0.006,3,1,0.550437,0,0.00
2,20,3,1,5,1,0.333218,0,0.006,3,1,0.550437,0,0.00
3,21,3,1,5,0,0.333218,0,0.006,3,0,0.550437,0,0.00
4,22,3,1,5,0,0.333218,0,0.006,3,0,0.550437,0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4723,24,4,1,3,1,0.550437,0,0.022,1,1,0.240536,0,0.03
4724,29,4,1,3,1,0.550437,0,0.022,1,1,0.240536,0,0.03
4725,32,5,2,3,1,0.550437,0,0.022,1,1,0.240536,0,0.03
4726,8,1,0,3,1,0.550437,0,0.022,1,1,0.240536,0,0.03
4727,16,2,2,3,1,0.550437,0,0.022,1,1,0.240536,0,0.03

In [7]:


successful_messages = pd.read_csv(
    f"dataset/{os.environ.get('DATASET')}/successful.csv"
)
print(f"successful messages columns: {successful_messages.columns}")

successful messages columns: Index(['messageId', 'lastRelay', 'destination'], dtype='object')

In [8]:
successful_messages

     messageId  lastRelay  destination
0           35          3            4
1           31          4            3
2           33          4            3
3           34          4            3
4           32          4            0
..         ...        ...          ...
894         27          3            1
895         28          3            1
896         12          3            1
897         15          3            1
898         30          3            1

[899 rows x 3 columns]

In [9]:


sent_messages = sent_messages[
    sent_messages["messageId"].isin(successful_messages["messageId"])
]

if sent_messages.shape[0] > 350000:
    sent_messages = sent_messages.sample(350000)

successful_messages = successful_messages[
    successful_messages["messageId"].isin(sent_messages["messageId"])
]

print("read the dataframes")

read the dataframes

In [10]:
successful_messages = successful_messages.reset_index(drop=True)

In [11]:

# make sure column is integer not float
sent_messages["usefulTransfer"] = pd.Series(dtype=np.int64)

print("initialized the dataframe")

initialized the dataframe

In [12]:
sent_messages = sent_messages.reset_index(drop=True)
sent_messages

,messageId,messageSource,messageHopCount,oldRelayId,oldFriendWithDestination,oldRelayBattery,oldCommonCommunity,oldDataMemory,newRelayId,newFriendWithDestination,newRelayBattery,newCommonCommunity,newDataMemory,usefulTransfer
0,18,3,1,5,1,0.333218,0,0.006,3,1,0.550437,0,0.00,NaN
1,19,3,1,5,1,0.333218,0,0.006,3,1,0.550437,0,0.00,NaN
2,20,3,1,5,1,0.333218,0,0.006,3,1,0.550437,0,0.00,NaN
3,21,3,1,5,0,0.333218,0,0.006,3,0,0.550437,0,0.00,NaN
4,22,3,1,5,0,0.333218,0,0.006,3,0,0.550437,0,0.00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4723,24,4,1,3,1,0.550437,0,0.022,1,1,0.240536,0,0.03,NaN
4724,29,4,1,3,1,0.550437,0,0.022,1,1,0.240536,0,0.03,NaN
4725,32,5,2,3,1,0.550437,0,0.022,1,1,0.240536,0,0.03,NaN
4726,8,1,0,3,1,0.550437,0,0.022,1,1,0.240536,0,0.03,NaN
4727,16,2,2,3,1,0.550437,0,0.022,1,1,0.240536,0,0.03,NaN

In [13]:
sent_messages.iloc[0]

messageId                   18.000000
messageSource                3.000000
messageHopCount              1.000000
oldRelayId                   5.000000
oldFriendWithDestination     1.000000
oldRelayBattery              0.333218
oldCommonCommunity           0.000000
oldDataMemory                0.006000
newRelayId                   3.000000
newFriendWithDestination     1.000000
newRelayBattery              0.550437
newCommonCommunity           0.000000
newDataMemory                0.000000
usefulTransfer                    NaN
Name: 0, dtype: float64

In [ ]:

sent_messages.loc[(sent_messages["usefulTransfer"] != 1), "usefulTransfer"] = 0
sent_messages = sent_messages.drop(
    columns=["messageId", "oldRelayId", "newRelayId", "messageSource"]
)
print(
    f"Number of useful transfers: {sent_messages['usefulTransfer'].value_counts()[1]}"
)

print(f"useful messages columns: {sent_messages.columns}")

In [ ]:

sent_messages.to_csv(
    f"dataset/{os.environ.get('DATASET')}/useful_messages.csv", index=False
)